swagger: '2.0'
info:
  version: 1.0.0
  title: Open Educational API
  x-logo:
    url: logo.png
host: api.openonderwijsapi.nl
basePath: /v1
schemes:
  - http
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  - application/xml
paths:
  /persons:
    get:
      summary: GET /persons
      description: An ordered (default by userId) list all persons.
      parameters:
        - name: pageNumber
          in: query
          description: The number of items to return per page
          required: false
          default: 1
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: The page number
          required: false
          default: 10
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: response
            required:
              - metadata
              - data
            properties:
              metadata:
                $ref: 'definitions/ListMetadata.yaml'
              data:
                type: array
                xml:
                  wrapped: true                
                items:
                  allOf:
                    - $ref: 'definitions/Person.yaml'
                    - xml:
                        name: item

  /persons/{userId}:
    get:
      summary: GET /persons/{userId}
      description: A single person.
      parameters:
        - name: userId
          in: path
          description: User ID
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            xml:
              name: response
            required:
              - metadata
              - data
            properties:
              metadata:
                $ref: 'definitions/ResourceMetadata.yaml'
              data:
                $ref: 'definitions/Person.yaml'
        '404':
          description: Not Found
