swagger: '2.0'
info:
  version: 1.0.0
  title: Open Education API
  x-logo:
    url: logo.png
host: api.openonderwijsapi.nl
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  - application/xml
tags:
  - name: persons
    description: The persons API provides information about persons related to an educational institute.
  - name: course results
    description: The course result API provides the (list of) test results from a specific course attended by a student.
  - name: buildings
    description: The building API provides general information about buildings in use by the organization. Updated daily.
  - name: test results
    description: The test result API provides information about the results from the tests from different courses done by the student. Updated daily.
paths:
  /persons:
    $ref: 'paths/PersonCollection.yaml'
  /persons/{userId}:
    $ref: 'paths/PersonInstance.yaml'
  /courseresults/{userId}:
    $ref: 'paths/CourseResultCollection.yaml'
  /courseresults/{userId}/{courseId}:
    $ref: 'paths/CourseResultInstance.yaml'
  /buildings:
    $ref: 'paths/BuildingCollection.yaml'
  /buildings/{buildingId}:
    $ref: 'paths/BuildingInstance.yaml'
  /testresults/{userId}:
    $ref: 'paths/TestResultCollection.yaml'
  /testresults/{userId}/{testId}:
    $ref: 'paths/TestResultInstance.yaml'
  /courses:
    $ref: 'paths/CourseCollection.yaml'
  /courses/{courseId}:
    $ref: 'paths/CourseInstance.yaml'
