swagger: '2.0'
info:
  version: 1.0.0
  title: Open Educational API
  x-logo:
    url: logo.png
host: api.openonderwijsapi.nl
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
  - application/xml
paths:
  /persons:
    $ref: 'paths/PersonCollection.yaml'
  /persons/{userId}:
    $ref: 'paths/PersonInstance.yaml'
